### ISSUE TITLE
Unable to run the read-only node

### ISSUE THREAD

**Issue by amishpopli** [Fantom-foundation/lachesis_launch#35]
Hi everyone,

I am new to the Fantom community. I am trying to run a read-only fantom node. I am following the steps as mentioned in this doc - https://github.com/Fantom-foundation/lachesis_launch/blob/master/docs/setup-readonly-node.sh

I was able to run the node when I first tried on my server, but unfortunately my server crashed due to memory constraints. I have been trying to run the node again but I keep getting the below error:

![image](https://user-images.githubusercontent.com/17144626/145730993-157613b3-2003-47f0-8967-0581dd73cc93.png)

Any help would be much appreciated :)

**Comment by quan8** [comment]
Hi @amishpopli, the db of your node seems to be corrupted. You may delete existing datadir, and try to resync again.
For nodes specs, please check: https://docs.fantom.foundation/staking/run-a-read-only-node
