### ISSUE TITLE
Fatal: Error starting protocol stack: fullsync isn't possible because state root is missing

### ISSUE THREAD

**Issue by chaerulchas** [Fantom-foundation/lachesis_launch#43]
Im Already test all the genesis file, but still getting this error

**Comment by quan8** [comment]
Hi @chaerulchas ,

May you give more details what steps / commands you've tried? which version of opera?

**Comment by chaerulchas** [comment]
Thanks @quan8 , Here its my steps 
```# Start opera node
(validator)$ cd build/
(validator)$ wget https://download.fantom.network/testnet-6226-no-mpt.g
(validator)$ nohup ./opera --genesis testnet-6226-no-mpt.g --nousb &```

**Comment by quan8** [comment]
@chaerulchas , which error did you get?

btw, what is ``` for?

**Comment by chaerulchas** [comment]
> @chaerulchas , which error did you get?
> 
> btw, what is ``` for?

nope sir, its wrong, im execute command without ```

**Comment by chaerulchas** [comment]
> @chaerulchas , which error did you get?
> 
> btw, what is ``` for?

im getting this error sir, 
Fatal: Error starting protocol stack: fullsync isn't possible because state root is missing
